[package]
name = "kidl-syn"
version = "0.1.0"
edition = "2021"

[dependencies]
rowan = "0.15.10"
ropey = "1.6.0"
unicode-ident = "1.0.7"

[dev-dependencies]
datatest-stable = "0.1.3"
snapdown = "1.0.0"

[[test]]
name = "lexer"
harness = false

[[test]]
name = "parser"
harness = false
