[package]
name = "kidl-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.10", features = ["derive"] }
kidl-syn = { path = "../kidl-syn" }
kidl-lsp = { path = "../kidl-lsp" }
tracing-subscriber = "0.3.16"
tracing = "0.1.37"
